
/**
 * @file node_basic.c
 *
 * Functions to allocate node structures
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: node_basic.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#include "node_basic.h"
#include "tree_basic.h"
#include "memory.h"
#include "dbug.h"
#include "globals.h"
#include "ctinfo.h"

static node *
MakeEmptyNode ()
{
  node *result;

  DBUG_ENTER ("MakeEmptyNode");

  result = (node *) MEMmalloc (sizeof (node));

  NODE_LINE (result) = global.line;
  NODE_COL (result) = global.col;

  DBUG_RETURN (result);
}



/*****************************************************************************
 * N_Program :
 *****************************************************************************/

node *
TBmakeProgram (node * Declarations, node * SymbolTable)
{
  node *this;
  DBUG_ENTER ("TBmakeProgram");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_program;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_program = MEMmalloc (sizeof (struct SONS_N_PROGRAM));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_program = MEMmalloc (sizeof (struct ATTRIBS_N_PROGRAM));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_program;
  DBUG_PRINT ("MAKE",
	      ("assigning son Declarations initial value: %s ",
	       Declarations));
  PROGRAM_DECLARATIONS (this) = Declarations;
  DBUG_PRINT ("MAKE",
	      ("assigning son SymbolTable initial value: %s ", SymbolTable));
  PROGRAM_SYMBOLTABLE (this) = SymbolTable;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((PROGRAM_DECLARATIONS (this) != NULL)
      && (NODE_TYPE (PROGRAM_DECLARATIONS (this)) != N_declarations))
    {
      CTIwarn
	("Field Declarations of node N_Program has non-allowed target node.");
    }
  if ((PROGRAM_SYMBOLTABLE (this) != NULL)
      && (NODE_TYPE (PROGRAM_SYMBOLTABLE (this)) != N_symbol))
    {
      CTIwarn
	("Field SymbolTable of node N_Program has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Symbol :
 *****************************************************************************/

node *
TBmakeSymbol (type Type, char *Name, int State, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeSymbol");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_symbol;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_symbol = MEMmalloc (sizeof (struct SONS_N_SYMBOL));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_symbol = MEMmalloc (sizeof (struct ATTRIBS_N_SYMBOL));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_symbol;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  SYMBOL_NEXT (this) = Next;
  SYMBOL_TYPE (this) = Type;
  SYMBOL_NAME (this) = Name;
  SYMBOL_STATE (this) = State;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((SYMBOL_NEXT (this) != NULL)
      && (NODE_TYPE (SYMBOL_NEXT (this)) != N_symbol))
    {
      CTIwarn ("Field Next of node N_Symbol has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Declarations :
 *****************************************************************************/

node *
TBmakeDeclarations (node * Decl, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeDeclarations");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_declarations;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_declarations = MEMmalloc (sizeof (struct SONS_N_DECLARATIONS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_declarations =
    MEMmalloc (sizeof (struct ATTRIBS_N_DECLARATIONS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_declarations;
  DBUG_PRINT ("MAKE", ("assigning son Decl initial value: %s ", Decl));
  DECLARATIONS_DECL (this) = Decl;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  DECLARATIONS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((DECLARATIONS_DECL (this) != NULL)
      && (NODE_TYPE (DECLARATIONS_DECL (this)) != N_fundef)
      && (NODE_TYPE (DECLARATIONS_DECL (this)) != N_globaldec)
      && (NODE_TYPE (DECLARATIONS_DECL (this)) != N_globaldef))
    {
      CTIwarn
	("Field Decl of node N_Declarations has non-allowed target node.");
    }
  if ((DECLARATIONS_NEXT (this) != NULL)
      && (NODE_TYPE (DECLARATIONS_NEXT (this)) != N_declarations))
    {
      CTIwarn
	("Field Next of node N_Declarations has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_FunDefs :
 *****************************************************************************/

node *
TBmakeFundefs (node * FunDef, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeFundefs");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_fundefs;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_fundefs = MEMmalloc (sizeof (struct SONS_N_FUNDEFS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_fundefs = MEMmalloc (sizeof (struct ATTRIBS_N_FUNDEFS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_fundefs;
  DBUG_PRINT ("MAKE", ("assigning son FunDef initial value: %s ", FunDef));
  FUNDEFS_FUNDEF (this) = FunDef;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  FUNDEFS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FUNDEFS_FUNDEF (this) != NULL)
      && (NODE_TYPE (FUNDEFS_FUNDEF (this)) != N_fundef))
    {
      CTIwarn ("Field FunDef of node N_FunDefs has non-allowed target node.");
    }
  if ((FUNDEFS_NEXT (this) != NULL)
      && (NODE_TYPE (FUNDEFS_NEXT (this)) != N_fundefs))
    {
      CTIwarn ("Field Next of node N_FunDefs has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_FunDef :
 *****************************************************************************/

node *
TBmakeFundef (type Type, char *Name, node * Params, node * FunBody,
	      node * SymbolTable)
{
  node *this;
  DBUG_ENTER ("TBmakeFundef");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_fundef;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_fundef = MEMmalloc (sizeof (struct SONS_N_FUNDEF));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_fundef = MEMmalloc (sizeof (struct ATTRIBS_N_FUNDEF));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_fundef;
  DBUG_PRINT ("MAKE", ("assigning son Params initial value: %s ", Params));
  FUNDEF_PARAMS (this) = Params;
  DBUG_PRINT ("MAKE", ("assigning son FunBody initial value: %s ", FunBody));
  FUNDEF_FUNBODY (this) = FunBody;
  DBUG_PRINT ("MAKE",
	      ("assigning son SymbolTable initial value: %s ", SymbolTable));
  FUNDEF_SYMBOLTABLE (this) = SymbolTable;
  FUNDEF_TYPE (this) = Type;
  FUNDEF_NAME (this) = Name;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FUNDEF_PARAMS (this) != NULL)
      && (NODE_TYPE (FUNDEF_PARAMS (this)) != N_param))
    {
      CTIwarn ("Field Params of node N_FunDef has non-allowed target node.");
    }
  if ((FUNDEF_FUNBODY (this) != NULL)
      && (NODE_TYPE (FUNDEF_FUNBODY (this)) != N_funbody))
    {
      CTIwarn ("Field FunBody of node N_FunDef has non-allowed target node.");
    }
  if ((FUNDEF_SYMBOLTABLE (this) != NULL)
      && (NODE_TYPE (FUNDEF_SYMBOLTABLE (this)) != N_symbol))
    {
      CTIwarn
	("Field SymbolTable of node N_FunDef has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_GlobalDef :
 *****************************************************************************/

node *
TBmakeGlobaldef (type Type, char *Name, node * Dims, node * Init)
{
  node *this;
  DBUG_ENTER ("TBmakeGlobaldef");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_globaldef;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_globaldef = MEMmalloc (sizeof (struct SONS_N_GLOBALDEF));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_globaldef = MEMmalloc (sizeof (struct ATTRIBS_N_GLOBALDEF));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_globaldef;
  DBUG_PRINT ("MAKE", ("assigning son Dims initial value: %s ", Dims));
  GLOBALDEF_DIMS (this) = Dims;
  DBUG_PRINT ("MAKE", ("assigning son Init initial value: %s ", Init));
  GLOBALDEF_INIT (this) = Init;
  GLOBALDEF_TYPE (this) = Type;
  GLOBALDEF_NAME (this) = Name;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((GLOBALDEF_DIMS (this) != NULL)
      && (NODE_TYPE (GLOBALDEF_DIMS (this)) != N_exprs))
    {
      CTIwarn ("Field Dims of node N_GlobalDef has non-allowed target node.");
    }
  if ((GLOBALDEF_INIT (this) != NULL)
      && (NODE_TYPE (GLOBALDEF_INIT (this)) != N_binop)
      && (NODE_TYPE (GLOBALDEF_INIT (this)) != N_monop)
      && (NODE_TYPE (GLOBALDEF_INIT (this)) != N_funcall)
      && (NODE_TYPE (GLOBALDEF_INIT (this)) != N_cast)
      && (NODE_TYPE (GLOBALDEF_INIT (this)) != N_var)
      && (NODE_TYPE (GLOBALDEF_INIT (this)) != N_num)
      && (NODE_TYPE (GLOBALDEF_INIT (this)) != N_float)
      && (NODE_TYPE (GLOBALDEF_INIT (this)) != N_bool)
      && (NODE_TYPE (GLOBALDEF_INIT (this)) != N_arrexpr))
    {
      CTIwarn ("Field Init of node N_GlobalDef has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_GlobalDec :
 *****************************************************************************/

node *
TBmakeGlobaldec (type Type, char *Name, node * Dims)
{
  node *this;
  DBUG_ENTER ("TBmakeGlobaldec");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_globaldec;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_globaldec = MEMmalloc (sizeof (struct SONS_N_GLOBALDEC));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_globaldec = MEMmalloc (sizeof (struct ATTRIBS_N_GLOBALDEC));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_globaldec;
  DBUG_PRINT ("MAKE", ("assigning son Dims initial value: %s ", Dims));
  GLOBALDEC_DIMS (this) = Dims;
  GLOBALDEC_TYPE (this) = Type;
  GLOBALDEC_NAME (this) = Name;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((GLOBALDEC_DIMS (this) != NULL)
      && (NODE_TYPE (GLOBALDEC_DIMS (this)) != N_ids))
    {
      CTIwarn ("Field Dims of node N_GlobalDec has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Ids :
 *****************************************************************************/

node *
TBmakeIds (char *Name, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeIds");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_ids;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_ids = MEMmalloc (sizeof (struct SONS_N_IDS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_ids = MEMmalloc (sizeof (struct ATTRIBS_N_IDS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_ids;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  IDS_NEXT (this) = Next;
  IDS_NAME (this) = Name;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((IDS_NEXT (this) != NULL) && (NODE_TYPE (IDS_NEXT (this)) != N_ids))
    {
      CTIwarn ("Field Next of node N_Ids has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_FunBody :
 *****************************************************************************/

node *
TBmakeFunbody (node * VarDec, node * LocalFunDefs, node * Statement)
{
  node *this;
  DBUG_ENTER ("TBmakeFunbody");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_funbody;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_funbody = MEMmalloc (sizeof (struct SONS_N_FUNBODY));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_funbody = MEMmalloc (sizeof (struct ATTRIBS_N_FUNBODY));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_funbody;
  DBUG_PRINT ("MAKE", ("assigning son VarDec initial value: %s ", VarDec));
  FUNBODY_VARDEC (this) = VarDec;
  DBUG_PRINT ("MAKE",
	      ("assigning son LocalFunDefs initial value: %s ",
	       LocalFunDefs));
  FUNBODY_LOCALFUNDEFS (this) = LocalFunDefs;
  DBUG_PRINT ("MAKE",
	      ("assigning son Statement initial value: %s ", Statement));
  FUNBODY_STATEMENT (this) = Statement;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FUNBODY_VARDEC (this) != NULL)
      && (NODE_TYPE (FUNBODY_VARDEC (this)) != N_vardec))
    {
      CTIwarn ("Field VarDec of node N_FunBody has non-allowed target node.");
    }
  if ((FUNBODY_LOCALFUNDEFS (this) != NULL)
      && (NODE_TYPE (FUNBODY_LOCALFUNDEFS (this)) != N_fundefs))
    {
      CTIwarn
	("Field LocalFunDefs of node N_FunBody has non-allowed target node.");
    }
  if ((FUNBODY_STATEMENT (this) != NULL)
      && (NODE_TYPE (FUNBODY_STATEMENT (this)) != N_stmts))
    {
      CTIwarn
	("Field Statement of node N_FunBody has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_VarDec :
 *****************************************************************************/

node *
TBmakeVardec (type Type, char *Name, node * Dims, node * Init, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeVardec");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_vardec;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_vardec = MEMmalloc (sizeof (struct SONS_N_VARDEC));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_vardec = MEMmalloc (sizeof (struct ATTRIBS_N_VARDEC));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_vardec;
  DBUG_PRINT ("MAKE", ("assigning son Dims initial value: %s ", Dims));
  VARDEC_DIMS (this) = Dims;
  DBUG_PRINT ("MAKE", ("assigning son Init initial value: %s ", Init));
  VARDEC_INIT (this) = Init;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  VARDEC_NEXT (this) = Next;
  VARDEC_TYPE (this) = Type;
  VARDEC_NAME (this) = Name;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((VARDEC_DIMS (this) != NULL)
      && (NODE_TYPE (VARDEC_DIMS (this)) != N_exprs))
    {
      CTIwarn ("Field Dims of node N_VarDec has non-allowed target node.");
    }
  if ((VARDEC_INIT (this) != NULL)
      && (NODE_TYPE (VARDEC_INIT (this)) != N_binop)
      && (NODE_TYPE (VARDEC_INIT (this)) != N_monop)
      && (NODE_TYPE (VARDEC_INIT (this)) != N_funcall)
      && (NODE_TYPE (VARDEC_INIT (this)) != N_cast)
      && (NODE_TYPE (VARDEC_INIT (this)) != N_var)
      && (NODE_TYPE (VARDEC_INIT (this)) != N_num)
      && (NODE_TYPE (VARDEC_INIT (this)) != N_float)
      && (NODE_TYPE (VARDEC_INIT (this)) != N_bool)
      && (NODE_TYPE (VARDEC_INIT (this)) != N_arrexpr))
    {
      CTIwarn ("Field Init of node N_VarDec has non-allowed target node.");
    }
  if ((VARDEC_NEXT (this) != NULL)
      && (NODE_TYPE (VARDEC_NEXT (this)) != N_vardec))
    {
      CTIwarn ("Field Next of node N_VarDec has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Param :
 *****************************************************************************/

node *
TBmakeParam (type Type, char *Name, node * Dims, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeParam");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_param;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_param = MEMmalloc (sizeof (struct SONS_N_PARAM));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_param = MEMmalloc (sizeof (struct ATTRIBS_N_PARAM));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_param;
  DBUG_PRINT ("MAKE", ("assigning son Dims initial value: %s ", Dims));
  PARAM_DIMS (this) = Dims;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  PARAM_NEXT (this) = Next;
  PARAM_TYPE (this) = Type;
  PARAM_NAME (this) = Name;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((PARAM_DIMS (this) != NULL) && (NODE_TYPE (PARAM_DIMS (this)) != N_ids))
    {
      CTIwarn ("Field Dims of node N_Param has non-allowed target node.");
    }
  if ((PARAM_NEXT (this) != NULL)
      && (NODE_TYPE (PARAM_NEXT (this)) != N_param))
    {
      CTIwarn ("Field Next of node N_Param has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Cast :
 *****************************************************************************/

node *
TBmakeCast (type Type, node * Expression)
{
  node *this;
  DBUG_ENTER ("TBmakeCast");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_cast;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_cast = MEMmalloc (sizeof (struct SONS_N_CAST));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_cast = MEMmalloc (sizeof (struct ATTRIBS_N_CAST));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_cast;
  DBUG_PRINT ("MAKE",
	      ("assigning son Expression initial value: %s ", Expression));
  CAST_EXPRESSION (this) = Expression;
  CAST_TYPE (this) = Type;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((CAST_EXPRESSION (this) != NULL)
      && (NODE_TYPE (CAST_EXPRESSION (this)) != N_binop)
      && (NODE_TYPE (CAST_EXPRESSION (this)) != N_monop)
      && (NODE_TYPE (CAST_EXPRESSION (this)) != N_funcall)
      && (NODE_TYPE (CAST_EXPRESSION (this)) != N_cast)
      && (NODE_TYPE (CAST_EXPRESSION (this)) != N_var)
      && (NODE_TYPE (CAST_EXPRESSION (this)) != N_num)
      && (NODE_TYPE (CAST_EXPRESSION (this)) != N_float)
      && (NODE_TYPE (CAST_EXPRESSION (this)) != N_bool)
      && (NODE_TYPE (CAST_EXPRESSION (this)) != N_arrexpr))
    {
      CTIwarn
	("Field Expression of node N_Cast has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_If :
 *****************************************************************************/

node *
TBmakeIf (node * Condition, node * IfBlock, node * ElseBlock)
{
  node *this;
  DBUG_ENTER ("TBmakeIf");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_if;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_if = MEMmalloc (sizeof (struct SONS_N_IF));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_if = MEMmalloc (sizeof (struct ATTRIBS_N_IF));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_if;
  DBUG_PRINT ("MAKE",
	      ("assigning son Condition initial value: %s ", Condition));
  IF_CONDITION (this) = Condition;
  DBUG_PRINT ("MAKE", ("assigning son IfBlock initial value: %s ", IfBlock));
  IF_IFBLOCK (this) = IfBlock;
  DBUG_PRINT ("MAKE",
	      ("assigning son ElseBlock initial value: %s ", ElseBlock));
  IF_ELSEBLOCK (this) = ElseBlock;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((IF_CONDITION (this) != NULL)
      && (NODE_TYPE (IF_CONDITION (this)) != N_binop)
      && (NODE_TYPE (IF_CONDITION (this)) != N_monop)
      && (NODE_TYPE (IF_CONDITION (this)) != N_funcall)
      && (NODE_TYPE (IF_CONDITION (this)) != N_cast)
      && (NODE_TYPE (IF_CONDITION (this)) != N_var)
      && (NODE_TYPE (IF_CONDITION (this)) != N_num)
      && (NODE_TYPE (IF_CONDITION (this)) != N_float)
      && (NODE_TYPE (IF_CONDITION (this)) != N_bool)
      && (NODE_TYPE (IF_CONDITION (this)) != N_arrexpr))
    {
      CTIwarn ("Field Condition of node N_If has non-allowed target node.");
    }
  if ((IF_IFBLOCK (this) != NULL)
      && (NODE_TYPE (IF_IFBLOCK (this)) != N_stmts))
    {
      CTIwarn ("Field IfBlock of node N_If has non-allowed target node.");
    }
  if ((IF_ELSEBLOCK (this) != NULL)
      && (NODE_TYPE (IF_ELSEBLOCK (this)) != N_stmts))
    {
      CTIwarn ("Field ElseBlock of node N_If has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_While :
 *****************************************************************************/

node *
TBmakeWhile (node * Condition, node * Block)
{
  node *this;
  DBUG_ENTER ("TBmakeWhile");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_while;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_while = MEMmalloc (sizeof (struct SONS_N_WHILE));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_while = MEMmalloc (sizeof (struct ATTRIBS_N_WHILE));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_while;
  DBUG_PRINT ("MAKE",
	      ("assigning son Condition initial value: %s ", Condition));
  WHILE_CONDITION (this) = Condition;
  DBUG_PRINT ("MAKE", ("assigning son Block initial value: %s ", Block));
  WHILE_BLOCK (this) = Block;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((WHILE_CONDITION (this) != NULL)
      && (NODE_TYPE (WHILE_CONDITION (this)) != N_binop)
      && (NODE_TYPE (WHILE_CONDITION (this)) != N_monop)
      && (NODE_TYPE (WHILE_CONDITION (this)) != N_funcall)
      && (NODE_TYPE (WHILE_CONDITION (this)) != N_cast)
      && (NODE_TYPE (WHILE_CONDITION (this)) != N_var)
      && (NODE_TYPE (WHILE_CONDITION (this)) != N_num)
      && (NODE_TYPE (WHILE_CONDITION (this)) != N_float)
      && (NODE_TYPE (WHILE_CONDITION (this)) != N_bool)
      && (NODE_TYPE (WHILE_CONDITION (this)) != N_arrexpr))
    {
      CTIwarn
	("Field Condition of node N_While has non-allowed target node.");
    }
  if ((WHILE_BLOCK (this) != NULL)
      && (NODE_TYPE (WHILE_BLOCK (this)) != N_stmts))
    {
      CTIwarn ("Field Block of node N_While has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_DoWhile :
 *****************************************************************************/

node *
TBmakeDowhile (node * Condition, node * Block)
{
  node *this;
  DBUG_ENTER ("TBmakeDowhile");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_dowhile;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_dowhile = MEMmalloc (sizeof (struct SONS_N_DOWHILE));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_dowhile = MEMmalloc (sizeof (struct ATTRIBS_N_DOWHILE));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_dowhile;
  DBUG_PRINT ("MAKE",
	      ("assigning son Condition initial value: %s ", Condition));
  DOWHILE_CONDITION (this) = Condition;
  DBUG_PRINT ("MAKE", ("assigning son Block initial value: %s ", Block));
  DOWHILE_BLOCK (this) = Block;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((DOWHILE_CONDITION (this) != NULL)
      && (NODE_TYPE (DOWHILE_CONDITION (this)) != N_binop)
      && (NODE_TYPE (DOWHILE_CONDITION (this)) != N_monop)
      && (NODE_TYPE (DOWHILE_CONDITION (this)) != N_funcall)
      && (NODE_TYPE (DOWHILE_CONDITION (this)) != N_cast)
      && (NODE_TYPE (DOWHILE_CONDITION (this)) != N_var)
      && (NODE_TYPE (DOWHILE_CONDITION (this)) != N_num)
      && (NODE_TYPE (DOWHILE_CONDITION (this)) != N_float)
      && (NODE_TYPE (DOWHILE_CONDITION (this)) != N_bool)
      && (NODE_TYPE (DOWHILE_CONDITION (this)) != N_arrexpr))
    {
      CTIwarn
	("Field Condition of node N_DoWhile has non-allowed target node.");
    }
  if ((DOWHILE_BLOCK (this) != NULL)
      && (NODE_TYPE (DOWHILE_BLOCK (this)) != N_stmts))
    {
      CTIwarn ("Field Block of node N_DoWhile has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_For :
 *****************************************************************************/

node *
TBmakeFor (char *LoopVar, node * Start, node * Stop, node * Step,
	   node * Block, node * SymbolTable)
{
  node *this;
  DBUG_ENTER ("TBmakeFor");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_for;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_for = MEMmalloc (sizeof (struct SONS_N_FOR));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_for = MEMmalloc (sizeof (struct ATTRIBS_N_FOR));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_for;
  DBUG_PRINT ("MAKE", ("assigning son Start initial value: %s ", Start));
  FOR_START (this) = Start;
  DBUG_PRINT ("MAKE", ("assigning son Stop initial value: %s ", Stop));
  FOR_STOP (this) = Stop;
  DBUG_PRINT ("MAKE", ("assigning son Step initial value: %s ", Step));
  FOR_STEP (this) = Step;
  DBUG_PRINT ("MAKE", ("assigning son Block initial value: %s ", Block));
  FOR_BLOCK (this) = Block;
  DBUG_PRINT ("MAKE",
	      ("assigning son SymbolTable initial value: %s ", SymbolTable));
  FOR_SYMBOLTABLE (this) = SymbolTable;
  FOR_LOOPVAR (this) = LoopVar;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FOR_START (this) != NULL) && (NODE_TYPE (FOR_START (this)) != N_binop)
      && (NODE_TYPE (FOR_START (this)) != N_monop)
      && (NODE_TYPE (FOR_START (this)) != N_funcall)
      && (NODE_TYPE (FOR_START (this)) != N_cast)
      && (NODE_TYPE (FOR_START (this)) != N_var)
      && (NODE_TYPE (FOR_START (this)) != N_num)
      && (NODE_TYPE (FOR_START (this)) != N_float)
      && (NODE_TYPE (FOR_START (this)) != N_bool)
      && (NODE_TYPE (FOR_START (this)) != N_arrexpr))
    {
      CTIwarn ("Field Start of node N_For has non-allowed target node.");
    }
  if ((FOR_STOP (this) != NULL) && (NODE_TYPE (FOR_STOP (this)) != N_binop)
      && (NODE_TYPE (FOR_STOP (this)) != N_monop)
      && (NODE_TYPE (FOR_STOP (this)) != N_funcall)
      && (NODE_TYPE (FOR_STOP (this)) != N_cast)
      && (NODE_TYPE (FOR_STOP (this)) != N_var)
      && (NODE_TYPE (FOR_STOP (this)) != N_num)
      && (NODE_TYPE (FOR_STOP (this)) != N_float)
      && (NODE_TYPE (FOR_STOP (this)) != N_bool)
      && (NODE_TYPE (FOR_STOP (this)) != N_arrexpr))
    {
      CTIwarn ("Field Stop of node N_For has non-allowed target node.");
    }
  if ((FOR_STEP (this) != NULL) && (NODE_TYPE (FOR_STEP (this)) != N_binop)
      && (NODE_TYPE (FOR_STEP (this)) != N_monop)
      && (NODE_TYPE (FOR_STEP (this)) != N_funcall)
      && (NODE_TYPE (FOR_STEP (this)) != N_cast)
      && (NODE_TYPE (FOR_STEP (this)) != N_var)
      && (NODE_TYPE (FOR_STEP (this)) != N_num)
      && (NODE_TYPE (FOR_STEP (this)) != N_float)
      && (NODE_TYPE (FOR_STEP (this)) != N_bool)
      && (NODE_TYPE (FOR_STEP (this)) != N_arrexpr))
    {
      CTIwarn ("Field Step of node N_For has non-allowed target node.");
    }
  if ((FOR_BLOCK (this) != NULL) && (NODE_TYPE (FOR_BLOCK (this)) != N_stmts))
    {
      CTIwarn ("Field Block of node N_For has non-allowed target node.");
    }
  if ((FOR_SYMBOLTABLE (this) != NULL)
      && (NODE_TYPE (FOR_SYMBOLTABLE (this)) != N_symbol))
    {
      CTIwarn
	("Field SymbolTable of node N_For has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Return :
 *****************************************************************************/

node *
TBmakeReturn (node * Expression)
{
  node *this;
  DBUG_ENTER ("TBmakeReturn");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_return;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_return = MEMmalloc (sizeof (struct SONS_N_RETURN));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_return = MEMmalloc (sizeof (struct ATTRIBS_N_RETURN));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_return;
  DBUG_PRINT ("MAKE",
	      ("assigning son Expression initial value: %s ", Expression));
  RETURN_EXPRESSION (this) = Expression;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((RETURN_EXPRESSION (this) != NULL)
      && (NODE_TYPE (RETURN_EXPRESSION (this)) != N_binop)
      && (NODE_TYPE (RETURN_EXPRESSION (this)) != N_monop)
      && (NODE_TYPE (RETURN_EXPRESSION (this)) != N_funcall)
      && (NODE_TYPE (RETURN_EXPRESSION (this)) != N_cast)
      && (NODE_TYPE (RETURN_EXPRESSION (this)) != N_var)
      && (NODE_TYPE (RETURN_EXPRESSION (this)) != N_num)
      && (NODE_TYPE (RETURN_EXPRESSION (this)) != N_float)
      && (NODE_TYPE (RETURN_EXPRESSION (this)) != N_bool)
      && (NODE_TYPE (RETURN_EXPRESSION (this)) != N_arrexpr))
    {
      CTIwarn
	("Field Expression of node N_Return has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Exprs :
 *****************************************************************************/

node *
TBmakeExprs (node * Exprs, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeExprs");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_exprs;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_exprs = MEMmalloc (sizeof (struct SONS_N_EXPRS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_exprs = MEMmalloc (sizeof (struct ATTRIBS_N_EXPRS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_exprs;
  DBUG_PRINT ("MAKE", ("assigning son Exprs initial value: %s ", Exprs));
  EXPRS_EXPRS (this) = Exprs;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  EXPRS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((EXPRS_EXPRS (this) != NULL)
      && (NODE_TYPE (EXPRS_EXPRS (this)) != N_binop)
      && (NODE_TYPE (EXPRS_EXPRS (this)) != N_monop)
      && (NODE_TYPE (EXPRS_EXPRS (this)) != N_funcall)
      && (NODE_TYPE (EXPRS_EXPRS (this)) != N_cast)
      && (NODE_TYPE (EXPRS_EXPRS (this)) != N_var)
      && (NODE_TYPE (EXPRS_EXPRS (this)) != N_num)
      && (NODE_TYPE (EXPRS_EXPRS (this)) != N_float)
      && (NODE_TYPE (EXPRS_EXPRS (this)) != N_bool)
      && (NODE_TYPE (EXPRS_EXPRS (this)) != N_arrexpr))
    {
      CTIwarn ("Field Exprs of node N_Exprs has non-allowed target node.");
    }
  if ((EXPRS_NEXT (this) != NULL)
      && (NODE_TYPE (EXPRS_NEXT (this)) != N_exprs))
    {
      CTIwarn ("Field Next of node N_Exprs has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Exprstmt :
 *****************************************************************************/

node *
TBmakeExprstmt (node * Expr)
{
  node *this;
  DBUG_ENTER ("TBmakeExprstmt");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_exprstmt;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_exprstmt = MEMmalloc (sizeof (struct SONS_N_EXPRSTMT));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_exprstmt = MEMmalloc (sizeof (struct ATTRIBS_N_EXPRSTMT));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_exprstmt;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  EXPRSTMT_EXPR (this) = Expr;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((EXPRSTMT_EXPR (this) != NULL)
      && (NODE_TYPE (EXPRSTMT_EXPR (this)) != N_binop)
      && (NODE_TYPE (EXPRSTMT_EXPR (this)) != N_monop)
      && (NODE_TYPE (EXPRSTMT_EXPR (this)) != N_funcall)
      && (NODE_TYPE (EXPRSTMT_EXPR (this)) != N_cast)
      && (NODE_TYPE (EXPRSTMT_EXPR (this)) != N_var)
      && (NODE_TYPE (EXPRSTMT_EXPR (this)) != N_num)
      && (NODE_TYPE (EXPRSTMT_EXPR (this)) != N_float)
      && (NODE_TYPE (EXPRSTMT_EXPR (this)) != N_bool)
      && (NODE_TYPE (EXPRSTMT_EXPR (this)) != N_arrexpr))
    {
      CTIwarn ("Field Expr of node N_Exprstmt has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Stmts :
 *****************************************************************************/

node *
TBmakeStmts (node * Stmt, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeStmts");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_stmts;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_stmts = MEMmalloc (sizeof (struct SONS_N_STMTS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_stmts = MEMmalloc (sizeof (struct ATTRIBS_N_STMTS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_stmts;
  DBUG_PRINT ("MAKE", ("assigning son Stmt initial value: %s ", Stmt));
  STMTS_STMT (this) = Stmt;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  STMTS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((STMTS_STMT (this) != NULL)
      && (NODE_TYPE (STMTS_STMT (this)) != N_assign)
      && (NODE_TYPE (STMTS_STMT (this)) != N_exprstmt)
      && (NODE_TYPE (STMTS_STMT (this)) != N_if)
      && (NODE_TYPE (STMTS_STMT (this)) != N_while)
      && (NODE_TYPE (STMTS_STMT (this)) != N_dowhile)
      && (NODE_TYPE (STMTS_STMT (this)) != N_for)
      && (NODE_TYPE (STMTS_STMT (this)) != N_return))
    {
      CTIwarn ("Field Stmt of node N_Stmts has non-allowed target node.");
    }
  if ((STMTS_NEXT (this) != NULL)
      && (NODE_TYPE (STMTS_NEXT (this)) != N_stmts))
    {
      CTIwarn ("Field Next of node N_Stmts has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Assign :
 *****************************************************************************/

node *
TBmakeAssign (node * Let, node * Expr)
{
  node *this;
  DBUG_ENTER ("TBmakeAssign");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_assign;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_assign = MEMmalloc (sizeof (struct SONS_N_ASSIGN));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_assign = MEMmalloc (sizeof (struct ATTRIBS_N_ASSIGN));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_assign;
  DBUG_PRINT ("MAKE", ("assigning son Let initial value: %s ", Let));
  ASSIGN_LET (this) = Let;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  ASSIGN_EXPR (this) = Expr;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((ASSIGN_LET (this) != NULL)
      && (NODE_TYPE (ASSIGN_LET (this)) != N_varlet))
    {
      CTIwarn ("Field Let of node N_Assign has non-allowed target node.");
    }
  if ((ASSIGN_EXPR (this) != NULL)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_binop)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_monop)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_funcall)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_cast)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_var)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_num)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_float)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_bool)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_arrexpr))
    {
      CTIwarn ("Field Expr of node N_Assign has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_BinOp :
 *****************************************************************************/

node *
TBmakeBinop (binop Op, node * Left, node * Right)
{
  node *this;
  DBUG_ENTER ("TBmakeBinop");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_binop;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_binop = MEMmalloc (sizeof (struct SONS_N_BINOP));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_binop = MEMmalloc (sizeof (struct ATTRIBS_N_BINOP));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_binop;
  DBUG_PRINT ("MAKE", ("assigning son Left initial value: %s ", Left));
  BINOP_LEFT (this) = Left;
  DBUG_PRINT ("MAKE", ("assigning son Right initial value: %s ", Right));
  BINOP_RIGHT (this) = Right;
  BINOP_OP (this) = Op;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((BINOP_LEFT (this) != NULL)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_binop)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_monop)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_funcall)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_cast)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_var)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_num)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_float)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_bool)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_arrexpr))
    {
      CTIwarn ("Field Left of node N_BinOp has non-allowed target node.");
    }
  if ((BINOP_RIGHT (this) != NULL)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_binop)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_monop)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_funcall)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_cast)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_var)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_num)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_float)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_bool)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_arrexpr))
    {
      CTIwarn ("Field Right of node N_BinOp has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_MonOp :
 *****************************************************************************/

node *
TBmakeMonop (monop Op, node * Operand)
{
  node *this;
  DBUG_ENTER ("TBmakeMonop");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_monop;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_monop = MEMmalloc (sizeof (struct SONS_N_MONOP));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_monop = MEMmalloc (sizeof (struct ATTRIBS_N_MONOP));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_monop;
  DBUG_PRINT ("MAKE", ("assigning son Operand initial value: %s ", Operand));
  MONOP_OPERAND (this) = Operand;
  MONOP_OP (this) = Op;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((MONOP_OPERAND (this) != NULL)
      && (NODE_TYPE (MONOP_OPERAND (this)) != N_binop)
      && (NODE_TYPE (MONOP_OPERAND (this)) != N_monop)
      && (NODE_TYPE (MONOP_OPERAND (this)) != N_funcall)
      && (NODE_TYPE (MONOP_OPERAND (this)) != N_cast)
      && (NODE_TYPE (MONOP_OPERAND (this)) != N_var)
      && (NODE_TYPE (MONOP_OPERAND (this)) != N_num)
      && (NODE_TYPE (MONOP_OPERAND (this)) != N_float)
      && (NODE_TYPE (MONOP_OPERAND (this)) != N_bool)
      && (NODE_TYPE (MONOP_OPERAND (this)) != N_arrexpr))
    {
      CTIwarn ("Field Operand of node N_MonOp has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_VarLet :
 *****************************************************************************/

node *
TBmakeVarlet (char *Name, node * Indices)
{
  node *this;
  DBUG_ENTER ("TBmakeVarlet");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_varlet;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_varlet = MEMmalloc (sizeof (struct SONS_N_VARLET));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_varlet = MEMmalloc (sizeof (struct ATTRIBS_N_VARLET));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_varlet;
  DBUG_PRINT ("MAKE", ("assigning son Indices initial value: %s ", Indices));
  VARLET_INDICES (this) = Indices;
  VARLET_NAME (this) = Name;
  VARLET_DECL (this) = NULL;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((VARLET_INDICES (this) != NULL)
      && (NODE_TYPE (VARLET_INDICES (this)) != N_exprs))
    {
      CTIwarn ("Field Indices of node N_VarLet has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Var :
 *****************************************************************************/

node *
TBmakeVar (char *Name, node * Indices)
{
  node *this;
  DBUG_ENTER ("TBmakeVar");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_var;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_var = MEMmalloc (sizeof (struct SONS_N_VAR));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_var = MEMmalloc (sizeof (struct ATTRIBS_N_VAR));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_var;
  DBUG_PRINT ("MAKE", ("assigning son Indices initial value: %s ", Indices));
  VAR_INDICES (this) = Indices;
  VAR_NAME (this) = Name;
  VAR_DECL (this) = NULL;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((VAR_INDICES (this) != NULL)
      && (NODE_TYPE (VAR_INDICES (this)) != N_exprs))
    {
      CTIwarn ("Field Indices of node N_Var has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Arrexpr :
 *****************************************************************************/

node *
TBmakeArrexpr (node * Exprs)
{
  node *this;
  DBUG_ENTER ("TBmakeArrexpr");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_arrexpr;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_arrexpr = MEMmalloc (sizeof (struct SONS_N_ARREXPR));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_arrexpr = MEMmalloc (sizeof (struct ATTRIBS_N_ARREXPR));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_arrexpr;
  DBUG_PRINT ("MAKE", ("assigning son Exprs initial value: %s ", Exprs));
  ARREXPR_EXPRS (this) = Exprs;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((ARREXPR_EXPRS (this) != NULL)
      && (NODE_TYPE (ARREXPR_EXPRS (this)) != N_exprs))
    {
      CTIwarn ("Field Exprs of node N_Arrexpr has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Funcall :
 *****************************************************************************/

node *
TBmakeFuncall (char *Name, node * Args)
{
  node *this;
  DBUG_ENTER ("TBmakeFuncall");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_funcall;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_funcall = MEMmalloc (sizeof (struct SONS_N_FUNCALL));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_funcall = MEMmalloc (sizeof (struct ATTRIBS_N_FUNCALL));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_funcall;
  DBUG_PRINT ("MAKE", ("assigning son Args initial value: %s ", Args));
  FUNCALL_ARGS (this) = Args;
  FUNCALL_NAME (this) = Name;
  FUNCALL_DECL (this) = NULL;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FUNCALL_ARGS (this) != NULL)
      && (NODE_TYPE (FUNCALL_ARGS (this)) != N_exprs))
    {
      CTIwarn ("Field Args of node N_Funcall has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Num :
 *****************************************************************************/

node *
TBmakeNum (int Value)
{
  node *this;
  DBUG_ENTER ("TBmakeNum");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_num;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_num = MEMmalloc (sizeof (struct SONS_N_NUM));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_num = MEMmalloc (sizeof (struct ATTRIBS_N_NUM));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_num;
  NUM_VALUE (this) = Value;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Float :
 *****************************************************************************/

node *
TBmakeFloat (float Value)
{
  node *this;
  DBUG_ENTER ("TBmakeFloat");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_float;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_float = MEMmalloc (sizeof (struct SONS_N_FLOAT));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_float = MEMmalloc (sizeof (struct ATTRIBS_N_FLOAT));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_float;
  FLOAT_VALUE (this) = Value;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Bool :
 *****************************************************************************/

node *
TBmakeBool (bool Value)
{
  node *this;
  DBUG_ENTER ("TBmakeBool");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_bool;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_bool = MEMmalloc (sizeof (struct SONS_N_BOOL));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_bool = MEMmalloc (sizeof (struct ATTRIBS_N_BOOL));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_bool;
  BOOL_VALUE (this) = Value;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Error :
 *****************************************************************************/

node *
TBmakeError (char *message, compiler_phase_t anyphase, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeError");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_error;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_error = MEMmalloc (sizeof (struct SONS_N_ERROR));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_error = MEMmalloc (sizeof (struct ATTRIBS_N_ERROR));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_error;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  ERROR_NEXT (this) = Next;
  ERROR_MESSAGE (this) = message;
  ERROR_ANYPHASE (this) = anyphase;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((ERROR_NEXT (this) != NULL)
      && (NODE_TYPE (ERROR_NEXT (this)) != N_error))
    {
      CTIwarn ("Field Next of node N_Error has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

  /* end of file */
