
/**
 * @file node_basic.h
 *
 * Functions to allocate node structures
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: node_basic.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_NODE_BASIC_H_
#define _SAC_NODE_BASIC_H_

#include "types.h"


#define _SAC_AST_VERSION_ "0.9"


/*****************************************************************************
 * macros and functions for N_program
 *****************************************************************************/

#define PROGRAM_DECLARATIONS( n) ((n)->sons.N_program->Declarations)
#define PROGRAM_SYMBOLTABLE( n) ((n)->sons.N_program->SymbolTable)
extern node *TBmakeProgram (node * Declarations, node * SymbolTable);

/*****************************************************************************
 * macros and functions for N_symbol
 *****************************************************************************/

#define SYMBOL_NEXT( n) ((n)->sons.N_symbol->Next)
#define SYMBOL_TYPE( n) ((n)->attribs.N_symbol->Type)
#define SYMBOL_NAME( n) ((n)->attribs.N_symbol->Name)
#define SYMBOL_STATE( n) ((n)->attribs.N_symbol->State)
extern node *TBmakeSymbol (type Type, char *Name, int State, node * Next);

/*****************************************************************************
 * macros and functions for N_declarations
 *****************************************************************************/

#define DECLARATIONS_DECL( n) ((n)->sons.N_declarations->Decl)
#define DECLARATIONS_NEXT( n) ((n)->sons.N_declarations->Next)
extern node *TBmakeDeclarations (node * Decl, node * Next);

/*****************************************************************************
 * macros and functions for N_fundefs
 *****************************************************************************/

#define FUNDEFS_FUNDEF( n) ((n)->sons.N_fundefs->FunDef)
#define FUNDEFS_NEXT( n) ((n)->sons.N_fundefs->Next)
extern node *TBmakeFundefs (node * FunDef, node * Next);

/*****************************************************************************
 * macros and functions for N_fundef
 *****************************************************************************/

#define FUNDEF_PARAMS( n) ((n)->sons.N_fundef->Params)
#define FUNDEF_FUNBODY( n) ((n)->sons.N_fundef->FunBody)
#define FUNDEF_SYMBOLTABLE( n) ((n)->sons.N_fundef->SymbolTable)
#define FUNDEF_TYPE( n) ((n)->attribs.N_fundef->Type)
#define FUNDEF_NAME( n) ((n)->attribs.N_fundef->Name)
extern node *TBmakeFundef (type Type, char *Name, node * Params,
			   node * FunBody, node * SymbolTable);

/*****************************************************************************
 * macros and functions for N_globaldef
 *****************************************************************************/

#define GLOBALDEF_DIMS( n) ((n)->sons.N_globaldef->Dims)
#define GLOBALDEF_INIT( n) ((n)->sons.N_globaldef->Init)
#define GLOBALDEF_TYPE( n) ((n)->attribs.N_globaldef->Type)
#define GLOBALDEF_NAME( n) ((n)->attribs.N_globaldef->Name)
extern node *TBmakeGlobaldef (type Type, char *Name, node * Dims,
			      node * Init);

/*****************************************************************************
 * macros and functions for N_globaldec
 *****************************************************************************/

#define GLOBALDEC_DIMS( n) ((n)->sons.N_globaldec->Dims)
#define GLOBALDEC_TYPE( n) ((n)->attribs.N_globaldec->Type)
#define GLOBALDEC_NAME( n) ((n)->attribs.N_globaldec->Name)
extern node *TBmakeGlobaldec (type Type, char *Name, node * Dims);

/*****************************************************************************
 * macros and functions for N_ids
 *****************************************************************************/

#define IDS_NEXT( n) ((n)->sons.N_ids->Next)
#define IDS_NAME( n) ((n)->attribs.N_ids->Name)
extern node *TBmakeIds (char *Name, node * Next);

/*****************************************************************************
 * macros and functions for N_funbody
 *****************************************************************************/

#define FUNBODY_VARDEC( n) ((n)->sons.N_funbody->VarDec)
#define FUNBODY_LOCALFUNDEFS( n) ((n)->sons.N_funbody->LocalFunDefs)
#define FUNBODY_STATEMENT( n) ((n)->sons.N_funbody->Statement)
extern node *TBmakeFunbody (node * VarDec, node * LocalFunDefs,
			    node * Statement);

/*****************************************************************************
 * macros and functions for N_vardec
 *****************************************************************************/

#define VARDEC_DIMS( n) ((n)->sons.N_vardec->Dims)
#define VARDEC_INIT( n) ((n)->sons.N_vardec->Init)
#define VARDEC_NEXT( n) ((n)->sons.N_vardec->Next)
#define VARDEC_TYPE( n) ((n)->attribs.N_vardec->Type)
#define VARDEC_NAME( n) ((n)->attribs.N_vardec->Name)
extern node *TBmakeVardec (type Type, char *Name, node * Dims, node * Init,
			   node * Next);

/*****************************************************************************
 * macros and functions for N_param
 *****************************************************************************/

#define PARAM_DIMS( n) ((n)->sons.N_param->Dims)
#define PARAM_NEXT( n) ((n)->sons.N_param->Next)
#define PARAM_TYPE( n) ((n)->attribs.N_param->Type)
#define PARAM_NAME( n) ((n)->attribs.N_param->Name)
extern node *TBmakeParam (type Type, char *Name, node * Dims, node * Next);

/*****************************************************************************
 * macros and functions for N_cast
 *****************************************************************************/

#define CAST_EXPRESSION( n) ((n)->sons.N_cast->Expression)
#define CAST_TYPE( n) ((n)->attribs.N_cast->Type)
extern node *TBmakeCast (type Type, node * Expression);

/*****************************************************************************
 * macros and functions for N_if
 *****************************************************************************/

#define IF_CONDITION( n) ((n)->sons.N_if->Condition)
#define IF_IFBLOCK( n) ((n)->sons.N_if->IfBlock)
#define IF_ELSEBLOCK( n) ((n)->sons.N_if->ElseBlock)
extern node *TBmakeIf (node * Condition, node * IfBlock, node * ElseBlock);

/*****************************************************************************
 * macros and functions for N_while
 *****************************************************************************/

#define WHILE_CONDITION( n) ((n)->sons.N_while->Condition)
#define WHILE_BLOCK( n) ((n)->sons.N_while->Block)
extern node *TBmakeWhile (node * Condition, node * Block);

/*****************************************************************************
 * macros and functions for N_dowhile
 *****************************************************************************/

#define DOWHILE_CONDITION( n) ((n)->sons.N_dowhile->Condition)
#define DOWHILE_BLOCK( n) ((n)->sons.N_dowhile->Block)
extern node *TBmakeDowhile (node * Condition, node * Block);

/*****************************************************************************
 * macros and functions for N_for
 *****************************************************************************/

#define FOR_START( n) ((n)->sons.N_for->Start)
#define FOR_STOP( n) ((n)->sons.N_for->Stop)
#define FOR_STEP( n) ((n)->sons.N_for->Step)
#define FOR_BLOCK( n) ((n)->sons.N_for->Block)
#define FOR_SYMBOLTABLE( n) ((n)->sons.N_for->SymbolTable)
#define FOR_LOOPVAR( n) ((n)->attribs.N_for->LoopVar)
extern node *TBmakeFor (char *LoopVar, node * Start, node * Stop, node * Step,
			node * Block, node * SymbolTable);

/*****************************************************************************
 * macros and functions for N_return
 *****************************************************************************/

#define RETURN_EXPRESSION( n) ((n)->sons.N_return->Expression)
extern node *TBmakeReturn (node * Expression);

/*****************************************************************************
 * macros and functions for N_exprs
 *****************************************************************************/

#define EXPRS_EXPRS( n) ((n)->sons.N_exprs->Exprs)
#define EXPRS_NEXT( n) ((n)->sons.N_exprs->Next)
extern node *TBmakeExprs (node * Exprs, node * Next);

/*****************************************************************************
 * macros and functions for N_exprstmt
 *****************************************************************************/

#define EXPRSTMT_EXPR( n) ((n)->sons.N_exprstmt->Expr)
extern node *TBmakeExprstmt (node * Expr);

/*****************************************************************************
 * macros and functions for N_stmts
 *****************************************************************************/

#define STMTS_STMT( n) ((n)->sons.N_stmts->Stmt)
#define STMTS_NEXT( n) ((n)->sons.N_stmts->Next)
extern node *TBmakeStmts (node * Stmt, node * Next);

/*****************************************************************************
 * macros and functions for N_assign
 *****************************************************************************/

#define ASSIGN_LET( n) ((n)->sons.N_assign->Let)
#define ASSIGN_EXPR( n) ((n)->sons.N_assign->Expr)
extern node *TBmakeAssign (node * Let, node * Expr);

/*****************************************************************************
 * macros and functions for N_binop
 *****************************************************************************/

#define BINOP_LEFT( n) ((n)->sons.N_binop->Left)
#define BINOP_RIGHT( n) ((n)->sons.N_binop->Right)
#define BINOP_OP( n) ((n)->attribs.N_binop->Op)
extern node *TBmakeBinop (binop Op, node * Left, node * Right);

/*****************************************************************************
 * macros and functions for N_monop
 *****************************************************************************/

#define MONOP_OPERAND( n) ((n)->sons.N_monop->Operand)
#define MONOP_OP( n) ((n)->attribs.N_monop->Op)
extern node *TBmakeMonop (monop Op, node * Operand);

/*****************************************************************************
 * macros and functions for N_varlet
 *****************************************************************************/

#define VARLET_INDICES( n) ((n)->sons.N_varlet->Indices)
#define VARLET_NAME( n) ((n)->attribs.N_varlet->Name)
#define VARLET_DECL( n) ((n)->attribs.N_varlet->Decl)
extern node *TBmakeVarlet (char *Name, node * Indices);

/*****************************************************************************
 * macros and functions for N_var
 *****************************************************************************/

#define VAR_INDICES( n) ((n)->sons.N_var->Indices)
#define VAR_NAME( n) ((n)->attribs.N_var->Name)
#define VAR_DECL( n) ((n)->attribs.N_var->Decl)
extern node *TBmakeVar (char *Name, node * Indices);

/*****************************************************************************
 * macros and functions for N_arrexpr
 *****************************************************************************/

#define ARREXPR_EXPRS( n) ((n)->sons.N_arrexpr->Exprs)
extern node *TBmakeArrexpr (node * Exprs);

/*****************************************************************************
 * macros and functions for N_funcall
 *****************************************************************************/

#define FUNCALL_ARGS( n) ((n)->sons.N_funcall->Args)
#define FUNCALL_NAME( n) ((n)->attribs.N_funcall->Name)
#define FUNCALL_DECL( n) ((n)->attribs.N_funcall->Decl)
extern node *TBmakeFuncall (char *Name, node * Args);

/*****************************************************************************
 * macros and functions for N_num
 *****************************************************************************/

#define NUM_VALUE( n) ((n)->attribs.N_num->Value)
extern node *TBmakeNum (int Value);

/*****************************************************************************
 * macros and functions for N_float
 *****************************************************************************/

#define FLOAT_VALUE( n) ((n)->attribs.N_float->Value)
extern node *TBmakeFloat (float Value);

/*****************************************************************************
 * macros and functions for N_bool
 *****************************************************************************/

#define BOOL_VALUE( n) ((n)->attribs.N_bool->Value)
extern node *TBmakeBool (bool Value);

/*****************************************************************************
 * macros and functions for N_error
 *****************************************************************************/

#define ERROR_NEXT( n) ((n)->sons.N_error->Next)
#define ERROR_MESSAGE( n) ((n)->attribs.N_error->message)
#define ERROR_ANYPHASE( n) ((n)->attribs.N_error->anyphase)
extern node *TBmakeError (char *message, compiler_phase_t anyphase,
			  node * Next);

#endif /* _SAC_NODE_BASIC_H_ */
