
/**
 * @file traverse_tables.c
 *
 * This file defines the function tables for traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: traverse_tables.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#include "traverse_tables.h"
#include "traverse_helper.h"
#include "print.h"
#include "copy_node.h"
#include "free_node.h"
#include "check.h"
#include "symbol_table.h"
#include "count_operators.h"
#include "opt_sub.h"


travtables_t travtables = {
  /* TR_undefined */
  {&TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror}

  /* TR_prt */
  , {&TRAVerror, &PRTprogram, &PRTsymbol, &PRTdeclarations, &PRTfundefs,
     &PRTfundef, &PRTglobaldef, &PRTglobaldec, &PRTids, &PRTfunbody,
     &PRTvardec, &PRTparam, &PRTcast, &PRTif, &PRTwhile, &PRTdowhile, &PRTfor,
     &PRTreturn, &PRTexprs, &PRTexprstmt, &PRTstmts, &PRTassign, &PRTbinop,
     &PRTmonop, &PRTvarlet, &PRTvar, &PRTarrexpr, &PRTfuncall, &PRTnum,
     &PRTfloat, &PRTbool, &PRTerror}

  /* TR_copy */
  , {&TRAVerror, &COPYprogram, &COPYsymbol, &COPYdeclarations, &COPYfundefs,
     &COPYfundef, &COPYglobaldef, &COPYglobaldec, &COPYids, &COPYfunbody,
     &COPYvardec, &COPYparam, &COPYcast, &COPYif, &COPYwhile, &COPYdowhile,
     &COPYfor, &COPYreturn, &COPYexprs, &COPYexprstmt, &COPYstmts,
     &COPYassign, &COPYbinop, &COPYmonop, &COPYvarlet, &COPYvar, &COPYarrexpr,
     &COPYfuncall, &COPYnum, &COPYfloat, &COPYbool, &COPYerror}

  /* TR_free */
  , {&TRAVerror, &FREEprogram, &FREEsymbol, &FREEdeclarations, &FREEfundefs,
     &FREEfundef, &FREEglobaldef, &FREEglobaldec, &FREEids, &FREEfunbody,
     &FREEvardec, &FREEparam, &FREEcast, &FREEif, &FREEwhile, &FREEdowhile,
     &FREEfor, &FREEreturn, &FREEexprs, &FREEexprstmt, &FREEstmts,
     &FREEassign, &FREEbinop, &FREEmonop, &FREEvarlet, &FREEvar, &FREEarrexpr,
     &FREEfuncall, &FREEnum, &FREEfloat, &FREEbool, &FREEerror}

  /* TR_chk */
  , {&TRAVerror, &CHKprogram, &CHKsymbol, &CHKdeclarations, &CHKfundefs,
     &CHKfundef, &CHKglobaldef, &CHKglobaldec, &CHKids, &CHKfunbody,
     &CHKvardec, &CHKparam, &CHKcast, &CHKif, &CHKwhile, &CHKdowhile, &CHKfor,
     &CHKreturn, &CHKexprs, &CHKexprstmt, &CHKstmts, &CHKassign, &CHKbinop,
     &CHKmonop, &CHKvarlet, &CHKvar, &CHKarrexpr, &CHKfuncall, &CHKnum,
     &CHKfloat, &CHKbool, &CHKerror}

  /* TR_sym */
  , {&TRAVerror, &SYMprogram, &TRAVsons, &SYMdeclarations, &SYMfundefs,
     &SYMfundef, &SYMglobaldef, &SYMglobaldec, &TRAVsons, &TRAVsons,
     &SYMvardec, &SYMparam, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &SYMfor, &TRAVsons, &TRAVsons, &TRAVsons, &SYMstmts, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons}

  /* TR_cop */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &COPbinop, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons}

  /* TR_os */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &OSbinop, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons}
};

preposttable_t pretable = {
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

preposttable_t posttable = {
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

const char *travnames[8] = {
  "unknown", "prt", "copy", "free", "chk", "sym", "cop", "os"
};
