
/**
 * @file traverse_helper.c
 *
 * Defines the helper function needed by the traversal system
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: traverse_helper.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */


#include "traverse_helper.h"
#include "dbug.h"
#include "tree_basic.h"
#include "traverse.h"

#define TRAV( son, info)    if (son != NULL) { son = TRAVdo( son, info); }

node *
TRAVnone (node * arg_node, info * arg_info)
{
  return (arg_node);
}

node *
TRAVerror (node * arg_node, info * arg_info)
{
  DBUG_ASSERT ((FALSE), "Illegal node type found.");

  return (arg_node);
}

node *
TRAVsons (node * arg_node, info * arg_info)
{
  switch (NODE_TYPE (arg_node))
    {
    case N_program:
      TRAV (PROGRAM_DECLARATIONS (arg_node), arg_info);
      TRAV (PROGRAM_SYMBOLTABLE (arg_node), arg_info);
      break;
    case N_symbol:
      TRAV (SYMBOL_NEXT (arg_node), arg_info);
      break;
    case N_declarations:
      TRAV (DECLARATIONS_DECL (arg_node), arg_info);
      TRAV (DECLARATIONS_NEXT (arg_node), arg_info);
      break;
    case N_fundefs:
      TRAV (FUNDEFS_FUNDEF (arg_node), arg_info);
      TRAV (FUNDEFS_NEXT (arg_node), arg_info);
      break;
    case N_fundef:
      TRAV (FUNDEF_PARAMS (arg_node), arg_info);
      TRAV (FUNDEF_FUNBODY (arg_node), arg_info);
      TRAV (FUNDEF_SYMBOLTABLE (arg_node), arg_info);
      break;
    case N_globaldef:
      TRAV (GLOBALDEF_DIMS (arg_node), arg_info);
      TRAV (GLOBALDEF_INIT (arg_node), arg_info);
      break;
    case N_globaldec:
      TRAV (GLOBALDEC_DIMS (arg_node), arg_info);
      break;
    case N_ids:
      TRAV (IDS_NEXT (arg_node), arg_info);
      break;
    case N_funbody:
      TRAV (FUNBODY_VARDEC (arg_node), arg_info);
      TRAV (FUNBODY_LOCALFUNDEFS (arg_node), arg_info);
      TRAV (FUNBODY_STATEMENT (arg_node), arg_info);
      break;
    case N_vardec:
      TRAV (VARDEC_DIMS (arg_node), arg_info);
      TRAV (VARDEC_INIT (arg_node), arg_info);
      TRAV (VARDEC_NEXT (arg_node), arg_info);
      break;
    case N_param:
      TRAV (PARAM_DIMS (arg_node), arg_info);
      TRAV (PARAM_NEXT (arg_node), arg_info);
      break;
    case N_cast:
      TRAV (CAST_EXPRESSION (arg_node), arg_info);
      break;
    case N_if:
      TRAV (IF_CONDITION (arg_node), arg_info);
      TRAV (IF_IFBLOCK (arg_node), arg_info);
      TRAV (IF_ELSEBLOCK (arg_node), arg_info);
      break;
    case N_while:
      TRAV (WHILE_CONDITION (arg_node), arg_info);
      TRAV (WHILE_BLOCK (arg_node), arg_info);
      break;
    case N_dowhile:
      TRAV (DOWHILE_CONDITION (arg_node), arg_info);
      TRAV (DOWHILE_BLOCK (arg_node), arg_info);
      break;
    case N_for:
      TRAV (FOR_START (arg_node), arg_info);
      TRAV (FOR_STOP (arg_node), arg_info);
      TRAV (FOR_STEP (arg_node), arg_info);
      TRAV (FOR_BLOCK (arg_node), arg_info);
      TRAV (FOR_SYMBOLTABLE (arg_node), arg_info);
      break;
    case N_return:
      TRAV (RETURN_EXPRESSION (arg_node), arg_info);
      break;
    case N_exprs:
      TRAV (EXPRS_EXPRS (arg_node), arg_info);
      TRAV (EXPRS_NEXT (arg_node), arg_info);
      break;
    case N_exprstmt:
      TRAV (EXPRSTMT_EXPR (arg_node), arg_info);
      break;
    case N_stmts:
      TRAV (STMTS_STMT (arg_node), arg_info);
      TRAV (STMTS_NEXT (arg_node), arg_info);
      break;
    case N_assign:
      TRAV (ASSIGN_LET (arg_node), arg_info);
      TRAV (ASSIGN_EXPR (arg_node), arg_info);
      break;
    case N_binop:
      TRAV (BINOP_LEFT (arg_node), arg_info);
      TRAV (BINOP_RIGHT (arg_node), arg_info);
      break;
    case N_monop:
      TRAV (MONOP_OPERAND (arg_node), arg_info);
      break;
    case N_varlet:
      TRAV (VARLET_INDICES (arg_node), arg_info);
      break;
    case N_var:
      TRAV (VAR_INDICES (arg_node), arg_info);
      break;
    case N_arrexpr:
      TRAV (ARREXPR_EXPRS (arg_node), arg_info);
      break;
    case N_funcall:
      TRAV (FUNCALL_ARGS (arg_node), arg_info);
      break;
    case N_num:
      break;
    case N_float:
      break;
    case N_bool:
      break;
    case N_error:
      TRAV (ERROR_NEXT (arg_node), arg_info);
      break;
    default:
      DBUG_ASSERT ((FALSE), "Illegal nodetype found!");
      break;
    }

  return (arg_node);
}

int
TRAVnumSons (node * node)
{
  int result = 0;

  DBUG_ENTER ("TRAVnumSons");

  switch (NODE_TYPE (node))
    {
    case N_program:
      result = 2;
      break;
    case N_symbol:
      result = 1;
      break;
    case N_declarations:
      result = 2;
      break;
    case N_fundefs:
      result = 2;
      break;
    case N_fundef:
      result = 3;
      break;
    case N_globaldef:
      result = 2;
      break;
    case N_globaldec:
      result = 1;
      break;
    case N_ids:
      result = 1;
      break;
    case N_funbody:
      result = 3;
      break;
    case N_vardec:
      result = 3;
      break;
    case N_param:
      result = 2;
      break;
    case N_cast:
      result = 1;
      break;
    case N_if:
      result = 3;
      break;
    case N_while:
      result = 2;
      break;
    case N_dowhile:
      result = 2;
      break;
    case N_for:
      result = 5;
      break;
    case N_return:
      result = 1;
      break;
    case N_exprs:
      result = 2;
      break;
    case N_exprstmt:
      result = 1;
      break;
    case N_stmts:
      result = 2;
      break;
    case N_assign:
      result = 2;
      break;
    case N_binop:
      result = 2;
      break;
    case N_monop:
      result = 1;
      break;
    case N_varlet:
      result = 1;
      break;
    case N_var:
      result = 1;
      break;
    case N_arrexpr:
      result = 1;
      break;
    case N_funcall:
      result = 1;
      break;
    case N_num:
      result = 0;
      break;
    case N_float:
      result = 0;
      break;
    case N_bool:
      result = 0;
      break;
    case N_error:
      result = 1;
      break;
    default:
      DBUG_ASSERT ((FALSE), "Illegal nodetype found!");
      break;
    }

  DBUG_RETURN (result);
}

node *
TRAVgetSon (int no, node * parent)
{
  node *result = NULL;

  DBUG_ENTER ("TRAVgetSon");

  switch (NODE_TYPE (parent))
    {
    case N_program:
      switch (no)
	{
	case 0:
	  result = PROGRAM_DECLARATIONS (parent);
	  break;
	case 1:
	  result = PROGRAM_SYMBOLTABLE (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_symbol:
      switch (no)
	{
	case 0:
	  result = SYMBOL_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_declarations:
      switch (no)
	{
	case 0:
	  result = DECLARATIONS_DECL (parent);
	  break;
	case 1:
	  result = DECLARATIONS_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_fundefs:
      switch (no)
	{
	case 0:
	  result = FUNDEFS_FUNDEF (parent);
	  break;
	case 1:
	  result = FUNDEFS_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_fundef:
      switch (no)
	{
	case 0:
	  result = FUNDEF_PARAMS (parent);
	  break;
	case 1:
	  result = FUNDEF_FUNBODY (parent);
	  break;
	case 2:
	  result = FUNDEF_SYMBOLTABLE (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_globaldef:
      switch (no)
	{
	case 0:
	  result = GLOBALDEF_DIMS (parent);
	  break;
	case 1:
	  result = GLOBALDEF_INIT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_globaldec:
      switch (no)
	{
	case 0:
	  result = GLOBALDEC_DIMS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_ids:
      switch (no)
	{
	case 0:
	  result = IDS_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_funbody:
      switch (no)
	{
	case 0:
	  result = FUNBODY_VARDEC (parent);
	  break;
	case 1:
	  result = FUNBODY_LOCALFUNDEFS (parent);
	  break;
	case 2:
	  result = FUNBODY_STATEMENT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_vardec:
      switch (no)
	{
	case 0:
	  result = VARDEC_DIMS (parent);
	  break;
	case 1:
	  result = VARDEC_INIT (parent);
	  break;
	case 2:
	  result = VARDEC_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_param:
      switch (no)
	{
	case 0:
	  result = PARAM_DIMS (parent);
	  break;
	case 1:
	  result = PARAM_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_cast:
      switch (no)
	{
	case 0:
	  result = CAST_EXPRESSION (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_if:
      switch (no)
	{
	case 0:
	  result = IF_CONDITION (parent);
	  break;
	case 1:
	  result = IF_IFBLOCK (parent);
	  break;
	case 2:
	  result = IF_ELSEBLOCK (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_while:
      switch (no)
	{
	case 0:
	  result = WHILE_CONDITION (parent);
	  break;
	case 1:
	  result = WHILE_BLOCK (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_dowhile:
      switch (no)
	{
	case 0:
	  result = DOWHILE_CONDITION (parent);
	  break;
	case 1:
	  result = DOWHILE_BLOCK (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_for:
      switch (no)
	{
	case 0:
	  result = FOR_START (parent);
	  break;
	case 1:
	  result = FOR_STOP (parent);
	  break;
	case 2:
	  result = FOR_STEP (parent);
	  break;
	case 3:
	  result = FOR_BLOCK (parent);
	  break;
	case 4:
	  result = FOR_SYMBOLTABLE (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_return:
      switch (no)
	{
	case 0:
	  result = RETURN_EXPRESSION (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_exprs:
      switch (no)
	{
	case 0:
	  result = EXPRS_EXPRS (parent);
	  break;
	case 1:
	  result = EXPRS_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_exprstmt:
      switch (no)
	{
	case 0:
	  result = EXPRSTMT_EXPR (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_stmts:
      switch (no)
	{
	case 0:
	  result = STMTS_STMT (parent);
	  break;
	case 1:
	  result = STMTS_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_assign:
      switch (no)
	{
	case 0:
	  result = ASSIGN_LET (parent);
	  break;
	case 1:
	  result = ASSIGN_EXPR (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_binop:
      switch (no)
	{
	case 0:
	  result = BINOP_LEFT (parent);
	  break;
	case 1:
	  result = BINOP_RIGHT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_monop:
      switch (no)
	{
	case 0:
	  result = MONOP_OPERAND (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_varlet:
      switch (no)
	{
	case 0:
	  result = VARLET_INDICES (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_var:
      switch (no)
	{
	case 0:
	  result = VAR_INDICES (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_arrexpr:
      switch (no)
	{
	case 0:
	  result = ARREXPR_EXPRS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_funcall:
      switch (no)
	{
	case 0:
	  result = FUNCALL_ARGS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_num:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_float:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_bool:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_error:
      switch (no)
	{
	case 0:
	  result = ERROR_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    default:
      DBUG_ASSERT ((FALSE), "Illegal nodetype found!");
      break;
    }

  DBUG_RETURN (result);
}
