
/**
 * @file types_nodetype.h
 *
 * This file defines the nodetype node enumeration.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: types_nodetype.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_NODETYPE_H_
#define _SAC_TYPES_NODETYPE_H_

#define MAX_NODES 31
typedef enum
{ N_undefined = 0, N_program = 1, N_symbol = 2, N_declarations =
    3, N_fundefs = 4, N_fundef = 5, N_globaldef = 6, N_globaldec = 7, N_ids =
    8, N_funbody = 9, N_vardec = 10, N_param = 11, N_cast = 12, N_if =
    13, N_while = 14, N_dowhile = 15, N_for = 16, N_return = 17, N_exprs =
    18, N_exprstmt = 19, N_stmts = 20, N_assign = 21, N_binop = 22, N_monop =
    23, N_varlet = 24, N_var = 25, N_arrexpr = 26, N_funcall = 27, N_num =
    28, N_float = 29, N_bool = 30, N_error = 31 } nodetype;

#endif /* _SAC_TYPES_NODETYPE_H_ */
